### ISSUE TITLE
Please add 'tapOffset' method to SLUIAElement class

### ISSUE THREAD

**Issue by rgonzo** [inkling/Subliminal#103]
Please add 'tapOffset' method to SLUIAElement class:
- (void)tapOffset: (NSString *)xCoord :(NSString *)yCoord {
  [self waitUntilTappable:YES thenSendMessage:[NSString stringWithFormat:@"tapWithOptions({ tapOffset: { x: %@, y: %@ } })",xCoord, yCoord]];
  }

**Comment by wearhere** [comment]
Can you please describe a use case for such a method, @rgonzo? I don't mean what the API would literally do, like the documentation says, but why you might want to tap at a point other than the element's [accessibility activation point](https://developer.apple.com/library/ios/documentation/uikit/reference/UIAccessibility_Protocol/Introduction/Introduction.html#//apple_ref/occ/instp/NSObject/accessibilityActivationPoint), which `-[SLUIAElement tap]` does. Perhaps you could change the activation point, rather than use an offset?

My concerns would be that a test using an offset wouldn't really mimic user interaction, because VoiceOver taps at the activation point of elements; and that it might be difficult to specify an offset in the tests relative to something meaningful--without just hardcoding one.

**Comment by wearhere** [comment]
Closing pending further comment.
