### ISSUE TITLE
Subliminal asserts differ from NSAssert by casting to BOOL, causing failure 6% of the time

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#13]
`NSAssert(object, @"description")` treats the assertion as true if the object is non-nil, and false if the object is `nil`.

Subliminal's asserts cast their passed expression to a BOOL: `BOOL __result = (expression)`. Unfortunately [casting a non-nil object to a BOOL will resolve to `NO` 6% of the time](http://www.mikeash.com/pyblog/friday-qa-2012-12-14-objective-c-pitfalls.html). One possible solution to this is to change everywhere that uses the `BOOL __result = (expression)` code is to change it to `BOOL __result = !!(expression)`. 

Unfortunately, the project I was working didn't have Suspicious Implicit Conversions warning on, so this bug threw me for quite a loop! If you do have the warning on, you'll get a warning about converting a pointer to a BOOL.

Example code demonstrating the bug and proposed solution:

https://gist.github.com/MaxGabriel/5734318

**Comment by wearhere** [comment]
Thanks for your repro cases! :thumbsup: I think that using `!!` sounds like a good solution.

`SLAssertTrue` was modeled after SenTest's `STAssertTrue` (see `SenTestCase_Macros.h`), which means that theirs is broken too, come to think of it... I wonder if their designers thought, because they called the macro "assert _true_" and not merely "assert", that users should be responsible for passing a boolean? But I think that it would be friendliest for Subliminal's to behave like `NSAssert`.

**Comment by aegolden** [comment]
This is a good suggestion (even though our assert macros have the "true" and "false" on the end Max is right that projects without all the warnings turned on could be caught off guard.  Pull request here: https://github.com/inkling/Subliminal/pull/17
