### ISSUE TITLE
Running in Jenkins fails with: "Failed to authorize rights (0x2) with status: -60007."

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#14]
I'm setting up Subliminal in Jenkins and I've got everything working, except I get this error when after the simulator launches:

```
Preparing to install app...

Resetting simulator content and settings...
Successfully reset iOS Simulator.

Setting simulator device type...
Successfully set simulator device type.


Launching tests...

Failed to authorize rights (0x2) with status: -60007.
Failed to authorize rights (0x2) with status: -60007.
```

Two things that might be different for me:
1. When I first tried to run the tests, an alert popped up on the Jenkins computer that said:

> GUI Scripting is not enabled
> Open System Preferences and check Enable Access for Assistive Devices in the Accessibility (or Universal Access) preference pane, then run this script again.

(I did so, then restarted the computer.)
1. The machine is running OS X 10.7.5

The error occurs regardless of passing the -login_password option or --live.

**Comment by MaxGabriel** [comment]
Ok, current strategy is to download mountain lion and try that out.

**Comment by wearhere** [comment]
The "GUI scripting" alert is expected; that preference needs to be enabled in order for `subliminal-test` to manipulate the simulator. Despite the alert, we should probably add that requirement to the "Continuous Integration" section of the README and to `subliminal-test`'s usage statement.

I think that "failure to authorize rights" message is related to http://openradar.appspot.com/radar?id=1544403 --Instruments prints that if you cancel the alert that appears when it tries to take control of the app for the first time. Instruments gives you two tries, hence two error messages.

Did you see [that alert](http://stackoverflow.com/questions/9476131/is-there-a-way-to-remove-the-authorization-prompt-from-command-line-instances-of), if you were watching your Jenkins instance run? I'm surprised that  `subliminal-test` didn't take care of it. Perhaps on Lion, the alert has a different structure than that expected by the `authorize_instruments` script.

**Comment by wearhere** [comment]
On Mountain Lion the username field is pre-filled, so `authorize_instruments` only needs the password; but maybe on Lion it's blank, like in the screenshot on that Stack Overflow thread?

**Comment by MaxGabriel** [comment]
Ok so I upgraded to Mountain Lion, but no luck there. It works fine when I go to the Jenkins machine and run the command locally, whether using `-login_password` or `--live` (so I know the password is correct). When I run from Jenkins, I never see the alert.

Our master Jenkins is run on AWS, and we connect to the slave iMac via SSH; not sure if that changes anything.

Nice catch with the SO thread; I had googled with the (0x2) still in place and got no results. I'm going to start trying the SO answers out.

**Comment by MaxGabriel** [comment]
Uh.. so I added the [security unlock step](http://stackoverflow.com/a/9678612/1176156) and [this step](http://stackoverflow.com/a/11416025/1176156) but that didn't work. Then I restarted the computer, and now the tests work.

I still get this message:

```
Failed to authorize rights (0x1) with status: -60007.
2013-06-09 15:28:02.143 instruments[973:1207] Failed to connect to local pid watcher service: (os/kern) failure
```

Pretty ridiculous. Thanks for your help Jeff. Is Travis any easier than this?

**Comment by wearhere** [comment]
There are a couple of reasons why Travis is very nice, but ease of running UIAutomation tests is not one of them, heh. At first we didn't have the VMs' password, so we couldn't authorize instruments any which way; and we still can't screen-share, which makes it difficult to debug e.g. simulator timeouts. The Travis guys have great support though and I'm hoping that they'll make further improvements.

I'm glad to hear the tests are working for you now. A little more context that may help us debug the issues that you were seeing:
- In my local testing, I only saw the alert once per restart. Maybe that's why you needed a restart too, to reset some state.
- The security unlock step never worked for me.
- The `/etc/authorization` modification did suppress the alert locally--but not on Travis. But then again, Travis was also weird in that the alert doesn't appear to show at all--Travis _just_ gets a command line prompt (which is what I get locally after canceling the alert).

The current CI guidance is to provide the user's password to try to submit to the alert/prompt because between my local testing and Travis it seemed that that was the only thing that would consistently work. I would bet that this is what actually worked for you too after restart, 'cause otherwise I don't think you would have got any "failed to authorize rights" message--which we see on Travis too, despite that the tests then run (lol). My suspicion is that the first authorization fails (you get two tries) and then the second succeeds.
