### ISSUE TITLE
System alerts in iOS 7[Question]

### ISSUE THREAD

**Issue by sreejithjanardhanan** [inkling/Subliminal#254]
Just wanted to ask you whether subliminal is capable of accessing system alerts in iOS 7. We tried to automate both inApp purchase and location alert and failed. We also tried UIAutomation tool and used record and playback option, but  result was the same. Code we followed for automating system alerts was sourced from your blog itself adding it below for reference.

SLAlert *buyAlert = [SLAlert alertWithTitle:@"Confirm Your In-App Purchase"];
SLAlertHandler *buyHandler = [buyAlert dismissWithButtonTitled:@"Buy"];
[SLAlertHandler addHandler:buyHandler];

Reference:https://www.inkling.com/engineering/subliminal/

**Comment by justinseanmartin** [comment]
My guess of the top of my head is that the hyphen being displayed in the alert title is not the standard ASCII one, but instead a UTF8 variant like EM_DASH (http://www.charbase.com/2014-unicode-em-dash).

**Comment by wearhere** [comment]
Were you testing in an iOS 7 device or simulator, @sreejithjanardhanan? Also, what does the failure you're seeing look like? i.e. does the alert pop up at all?

I ask because I can't test in-app purchase in the iOS 7 Simulator--prices won't load. This was [a known issue (rdar://13962338)](https://developer.apple.com/library/mac/releasenotes/DeveloperTools/RN-Xcode/xc5_release_notes/xc5_release_notes.html#//apple_ref/doc/uid/TP40001051-CH2-SW1) at least as of Xcode 5.0.1 and, though the release notes don't comment either way, doesn't appear to have been fixed for Xcode 5.1.1.

However, I just tested on an iOS 7 device and the code above worked. (Good guess though @justinseanmartin.)

Two in-app purchase testing preliminaries of which you may or may not be aware: 
- you must make sure to change your test target's bundle identifier to that of your main target;
- and, because two applications with the same identifier cannot be installed simultaneously, you must uninstall any copies of your app before/after testing.

If you are testing from the command line, `subliminal-test` can handle the above steps for you using the `-replacement_bundle_id` option.

**Comment by wearhere** [comment]
Broadly speaking, Subliminal should be able to handle any system alerts. I have to run at the moment but I'm pretty sure I've successfully tested the location alert too. Can you describe what you're trying in that case?

**Comment by sreejithjanardhanan** [comment]
Thanks for your replies. We tried in both simulator and phone. And you are right about the fact that in-app purchase dialog wont appear in simulator. 

Lets leave aside subliminal for the moment. Will tell you what I tried using UIAutomation. 

Consider an app that requires location so that when  app launches a location alert will be shown. we tried the record an playback feature of UIAutomation  tool and in iOS 6. We successfully recorded  and played back the interaction with location alert. But in iOS 7 interaction with location alert was not recorded. 

Since subliminal is based on UIAutomation wont a similar problem occur in here as well ? I will check the system alert interaction using subliminal once more and will reply back.

**Comment by wearhere** [comment]
Ah, I think what you're seeing as regards recording is that, as of iOS 7, system alerts have become [remote views](http://oleb.net/blog/2012/10/remote-view-controllers-in-ios-6/). Instruments will not _record_ interaction in these views, as they belong to another process than your app. However, the views are still accessible, and Instruments will fortunately _play back_ commands that manipulate those views--commands like those issued by Subliminal.

Note that Subliminal cannot handle alerts that appear before the tests start up, as it has to load its alert handling system (and your tests have got to add handlers). [This Stack Overflow answer](http://stackoverflow.com/a/18726639/495611) gives some suggestions for delaying the alerts.

**Comment by sreejithjanardhanan** [comment]
@wearhere  Thank you for your answer. Delay part was the key in here. Now it works well.
