### ISSUE TITLE
Is it possible for me to re-run the script?

### ISSUE THREAD

**Issue by KenLau** [inkling/Subliminal#262]
I tried it, it's amazing for developers. However, every time, i start running the app through Instrument, and the test script finished, i cannot re-run it, when i press the run button in the bottom, it start loading with the cursor, but nothing happened, is it a bug or feature that will be added later?

**Comment by wearhere** [comment]
Hi @KenLau, it sounds like you're trying to use the run button at the bottom of Instruments as shown in [this picture](http://blog.manbolo.com/2012/04/08/uiautomation-1.png). Those buttons do re-run the script--but without re-starting the app (which is crucial for Subliminal because the script doesn't do anything by itself, it just receives commands from your tests inside the app).

To re-start the script _and_ the app, press the run/record button in the upper left hand corner of Instruments. Also make sure you have "Run on Record" checked in the left column on Instruments (as I think is the default). Confusing design I know. :)

You can also restart the script and app by selecting Profile again in Xcode (what you used to launch Instruments). This will also build any changes to your app, so you can do this to try changes to the app/your tests without having to relaunch Instruments.

**Comment by wearhere** [comment]
@KenLau I'm going to close this until I hear that the instructions above don't work or I missed something--please let me know if so. Thanks!
