### ISSUE TITLE
Can't build workspace using subliminal-test

### ISSUE THREAD

**Issue by MaxGabriel** [inkling/Subliminal#31]
I'm using standard CI script from the README to run Subliminal through Jenkins, except I'm using Cocoapods, so I need to choose a workspace to build:

```
# Run the tests in the non-retina iPhone Simulator
DEVICE="iPhone"

OUTPUT_DIR=test-reports
mkdir -p OUTPUT_DIR

# Returns 0 on success, 1 on failure
# Log output and screenshots will be placed in $OUTPUT_DIR
"ios-sdk/Heyzap/Pods/Subliminal/Supporting Files/CI/subliminal-test" -workspace "ios-sdk/Heyzap/Heyzap.xcworkspace" -sim_device "$DEVICE" -output "$OUTPUT_DIR" -login_password "hunter2"
```

But when I run the script I get the following error:

```
Building app...
Build settings from command line:
    SDKROOT = iphonesimulator6.1
    SYMROOT = /tmp/subliminal-test.build.gVh4uT
    TARGETED_DEVICE_FAMILY = 1
    VALIDATE_PRODUCT = NO

xcodebuild: error: '' is not a project file.


ERROR: Could not build application.
```

The script works fine against a standard `.xcodeproj` file.

**Comment by MaxGabriel** [comment]
Ah, now that I check the `subliminal-test` script, it looks like it isn't using the workspace argument at all:

```
$BUILD_TOOL\
        -project "$PROJECT"\
        -scheme "$SCHEME"\
        -configuration "$CONFIGURATION"\
        -sdk "$SDK"\
        $TARGETED_DEVICE_FAMILY_ARG\
        SYMROOT="$BUILD_DIR"\
        VALIDATE_PRODUCT=NO\
        clean build
```

**Comment by MaxGabriel** [comment]
Cool, so swapping out the `-project "$PROJECT"` argument with `-workspace "$WORKSPACE"` fixes it for me, though obviously there's still a bug in the script. I don't really know any shell scripting -- is there a good way to express that if `$PROJECT` is blank, use `-workspace "$WORKSPACE"`, else use `-project "$PROJECT"` ?

**Comment by wearhere** [comment]
Good catch @MaxGabriel! Can you try building your workspace off of https://github.com/inkling/Subliminal/tree/jeff/respect_workspace_arg? It looks like `subliminal-test` will now properly prepare a workspace build command but I don't have any to build.

**Comment by wearhere** [comment]
@MaxGabriel, despite Travis' current failure on https://github.com/inkling/Subliminal/tree/jeff/respect_workspace_arg, it'd still be worth giving it a try--it's failed due to a quirk of executing the `reset_simulator` Applescript which has never occurred in our testing either locally or using Jenkins... only when using Travis. >.< Any failure is, of course, unacceptable, and I'll be looking into replacing the script tomorrow, but you might find that the branch works for you even as is.

**Comment by MaxGabriel** [comment]
Well one thing's for certain, I probably shouldn't be testing your changes on master...

**Comment by wearhere** [comment]
Heh, did you mean because of the test failure, or because of the rebasing? It looks a bit hairy here, as the issue collects the commits that tag it, but imo makes the commit history much easier to read and ensures that commits that break the build never go into master (both on principle and so that we could run `git bisect` at some later point).

Anyway #34 is good now and will probably be merged Monday, I've asked my coworkers to review the request when they have a chance.

**Comment by MaxGabriel** [comment]
Haha no, I just forgot to switch to your branch entirely. It was late.
