### ISSUE TITLE
App Hook fails when registering a method defined in superclass' category

### ISSUE THREAD

**Issue by nicnocquee** [inkling/Subliminal#68]
@aegolden thanks for answering my question in [SO](http://stackoverflow.com/questions/18254163/how-to-simulate-table-view-or-collection-view-scrolling-using-kif-or-subliminal). It works. 

I tried to play around with AppHook but it seems like registering a selector which is defined in superclass' category doesn't work.

For example, in [my sample app](https://github.com/nicnocquee/TestSubliminal), I put the method `scrollToBottom` in the category of `UICollectionViewController`. But when I register 

```
[[SLTestController sharedTestController] registerTarget:self forAction:@selector(scrollToBottom)];
```

in `ViewController` (subclass of `UICollectionViewController`), I got

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Target <ViewController: 0x7144080> does not respond to action: scrollToBottom'
```

Any idea?

**Comment by wearhere** [comment]
It looks like the problem was that the category wasn't linked with the integration tests target:

![napkin 08-17-13 10 10 12 pm](https://f.cloud.github.com/assets/110000/982092/77e7bf26-07c4-11e3-9855-2da5f3024c21.png)

Easy enough to miss! The app would compile just fine because nothing called `scrollToBottom` directly, but at runtime, the method wouldn't be found. When `UICollectionViewController+Additions.m` is added to the integration tests target, the test passes fine.

**Comment by nicnocquee** [comment]
OMG! You're right! Thanks :)
