### ISSUE TITLE
Revise Subliminal's documentation.

### ISSUE THREAD

**Issue by wearhere** [inkling/Subliminal#82]
- [x] Migrate installation process to wiki page to slim the README

EDIT: This issue used to talk about adding contributing guidelines but that was moved to #166.

**Comment by MaxGabriel** [comment]
Hey @wearhere do you still want to have most of the README moved to the wiki? That'd be pretty easy for me to do.

**Comment by MaxGabriel** [comment]
My plan on moving to the wiki is that I'll move content over to the wiki gradually, where it's available for public review. Unfortunately, I don't think there's any PR system, so I'll just add things and let them be reviewed over time.

Based on the README, I think these are good candidates for being broken out into separate wiki pages:
- [x] [Create the Integration Tests Target page](https://github.com/inkling/Subliminal/wiki/Create-the-Integration-Tests-Target)
- [x] [Install Subliminal with Git submodules](https://github.com/inkling/Subliminal/wiki/Install-Subliminal-With-Git-Submodules-or-Manually)
- [x] [Add Test Running Code to the Target](https://github.com/inkling/Subliminal/wiki/Add-Test-Running-Code-to-the-Target)
  - Added loading Instruments and choosing the Subliminal template
- [x] [Writing Tests](https://github.com/inkling/Subliminal/wiki/Writing-Tests)
  - Added making a new Subliminal test case using the file template
- [x] [Debugging](https://github.com/inkling/Subliminal/wiki/Debugging-Tests)
  - Added a section on logging
- [x] [Continuous Integration](https://travis-ci.org/MaxGabriel/TestTravis)
  - With a section on Travis CI specifically
    - I tested the `.travis.yml` file [with this project](https://travis-ci.org/MaxGabriel/TestTravis)
- [x] Add linkage between wiki pages
- [x] [Wiki front page](https://github.com/inkling/Subliminal/wiki)
  - Missing link to CI page atm
- [x] [Known Issues](https://github.com/inkling/Subliminal/wiki/Known-Issues)
  - I didn't initially plan to add this to the README, but after removing the rest of the README it didn't really fit in. Also I consider it a niche enough topic to not be on the README
- [x] PR to add the images to gh-pages branch; see #161
- [x] PR to remove this stuff from the README; see #160
- [ ] After everything else, update the GH pages branch (a slimmer README would help it alot, so you can actually see the links to the API docs)

I'll be adding new images as I go (The 1st page now has new images updated for Xcode 5). I'm just hotlinking images from my fork of Subliminal while I work, and I'll replace them with images from the gh-pages branch in a PR ([you can host them on the git repo backing the wiki itself](http://stackoverflow.com/a/12453272/1176156), but I don't plan on doing that because there's no web interface to upload/view them, and I think you need push access to add them).

**Comment by wearhere** [comment]
This sounds like a solid plan. The Integration Tests target page looks good so far--I'd agree that renaming the scheme would be a good candidate for discussion there too since that's also part of target setup.

I also like the idea of a section on Travis CI specifically. Travis has a couple of huge advantages (it's free and easy to set up, with really nice GitHub integration and output) and drawbacks (instability… with zero access to debug) that people ought to know about.

(By the way, I don't think we should include the login password as part of our docs without asking Travis support, but Travis _might_ not actually require the login password: see https://github.com/travis-ci/travis-ci/issues/1292, whose status is unclear to me.)

Lastly I like putting the images in the `gh-pages` branch rather than in the wiki repo, I agree that seems a bit tricky to access.

**Comment by MaxGabriel** [comment]
More pages are up for review. The [Add Test Running Code to the Target](https://github.com/inkling/Subliminal/wiki/Add-Test-Running-Code-to-the-Target) added a step on loading Instruments and choosing the Subliminal template, which I thought out of place in its current location (pretty far down in the README, even after topics like CI and comparisons to other frameworks.

[Writing Tests](https://github.com/inkling/Subliminal/wiki/Writing-Tests) added a note about making a new Subliminal test case using the file template. This page I don't feel great about: there's alot more public interface available (like all the subclasses of `SLElement`, the different SLAsserts), but the wiki doesn't have a good route to learning more about that kind of stuff. This section is a good area for improvement, but I'm just moving on to the other pages for now.

Re: Travis. You know alot more about the Travis stuff than me, so I'll leave out the password part (I've seen it work fine without it, atleast).

**Comment by MaxGabriel** [comment]
@wearhere Can the [README part on enabling GUI scripting](https://github.com/inkling/Subliminal#continuous-integration) be dropped for CI be dropped? I notice that on the Subliminal Travis builds that there's an error about it not being enabled, but the tests run fine. https://travis-ci.org/inkling/Subliminal/jobs/21650554

**Comment by wearhere** [comment]
These new pages look good @MaxGabriel.

I definitely agree with 

> There's alot more public interface available (like all the subclasses of SLElement, the different SLAsserts), but the wiki doesn't have a good route to learning more about that kind of stuff. 

A page like "The Structure of a Test", to which "In the body of those tests, you do some work and then make some assertions" in [Writing Tests](https://github.com/inkling/Subliminal/wiki/Writing-Tests) could link, might be useful. More examples and screencasts might help too.

The success of #158 appears to confirm that Travis _is_ pre-authorized (travis-ci/travis-ci#1292). We can drop the GUI scripting stuff if we can confirm that such pre-authorization works in other environments e.g. locally and on Jenkins--and especially on Mavericks cause Travis isn't using that yet and travis-ci/travis-ci#1292 mentions that the pre-authorization method changes.

**Comment by MaxGabriel** [comment]
Ok @wearhere ready for final review I think.

**Comment by wearhere** [comment]
The wiki looks great @MaxGabriel. There's a lot of info there but it's well-organized. I like that every step in installation is just a couple of lines. It's also pretty clear to me where Cocoapods instructions will go, just as an alternative second install step.

I've gone through and made some minor edits for clarity. The only major change was to remove the discussion about the Travis login password altogether--I think it's simpler if we just assume that Travis will remain able to be pre-authorized. Apart from authorization, the login password _is_ required currently in order to test on the 5.1 and 6.1 SDKs, but since this will change shortly--when Travis updates to Xcode 5.1--I'm comfortable leaving a bug report in there for now.

So, the wiki looks good. I think the README is maybe a little _too_ slim now (see my comments on #160) but we're pretty close.

**Comment by wearhere** [comment]
Btw I may have limited internet access for the next couple of days but I'll try to make comments as able.

**Comment by wearhere** [comment]
The README is now so fresh, so clean thanks to @MaxGabriel. Moving the discussion around contributing guidelines to its own issue: #166.

**Comment by MaxGabriel** [comment]
Thanks @wearhere
