### ISSUE TITLE
Subliminal doesn't work using Xcode 5.0.1 (because UIAutomation doesn't work under Xcode 5.0.1)

### ISSUE THREAD

**Issue by pockany** [inkling/Subliminal#98]
Subliminal doesn't work using Xcode 5.0.1. It is because UIAutomation doesn't work under Xcode 5.0.1 . It is an Apple bug, and there is nothing we can do to fix it. The exact problem is described here : https://devforums.apple.com/message/910612 . Multiple bugreports have already been sent to them about this problem from the Apple Developer Community.

**Comment by wearhere** [comment]
Thanks for filing a report, @pockany. Whatever issue exists appears to be particular to certain installations--I've been running 5.0.1 for weeks without issue--on Mountain Lion. On the other hand, on Mavericks, I am able to run tests against the 6.1 SDK, but not the 7.0 SDK/simulator.

Note also that since Xcode 5, there's been an issue where Instruments fails to launch tests in a 6.1 Simulator, saying something like "target application is frontmost". But _that_ issue can be reliably resolved by quitting the simulator, then pressing record again.

In the forums, the Apple rep suggests that afflicted users try Xcode 5. That's what we'd suggest as well. Hopefully 5.0.2 will improve the situation.

**Comment by wearhere** [comment]
Since there's nothing that Subliminal can do about these bugs, I've summarized our discussion here in the "Known Issues" section of the README and will now close this issue. Please let us know if there's anything we can do to help, though--and if you hear about these bugs being fixed before we do, please pass the good word along! :)

**Comment by tulushev** [comment]
Xcode 5.0.2 is here, with fix to UIAutomation.
